module.exports = {
  apps: [
    {
      name: 'lptv-proxy',
      script: 'scripts/proxy-server.cjs',
      cwd: '.',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env_development: {
        NODE_ENV: 'development',
        PORT: 3000,
        ALLOWED_ORIGINS: 'http://localhost:5173,http://127.0.0.1:5173',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: process.env.PORT || 3000,
        ALLOWED_ORIGINS: process.env.ALLOWED_ORIGINS || '',
        IPTV345_TOKEN: process.env.IPTV345_TOKEN || '',
        IPTV345_KRKAN: process.env.IPTV345_KRKAN || '',
        IPTV345_ARNAK: process.env.IPTV345_ARNAK || '',
        IPTV345_NBYSB: process.env.IPTV345_NBYSB || '',
      },
      error_file: 'logs/error.log',
      out_file: 'logs/out.log',
      log_file: 'logs/combined.log',
      time: true,
    },
    {
      name: 'lptv-frontend',
      script: './node_modules/.bin/vite',
      args: 'serve --port 5173 --strictPort',
      cwd: '.',
      instances: 1,
      autorestart: true,
      watch: false,
      env_development: { NODE_ENV: 'development' },
      env_production: { NODE_ENV: 'production' },
      error_file: 'logs/frontend-error.log',
      out_file: 'logs/frontend-out.log',
      log_file: 'logs/frontend-combined.log',
      time: true,
    },
  ],
}
