import { IptvChannel } from '../data/iptvChannels';

const LOGO_BASE = '/api/proxy/logo';

const channelLogoMap: Record<string, string> = {
  'CCTV1 综合': 'CCTV1',
  'CCTV2 财经': 'CCTV2',
  'CCTV3 综艺': 'CCTV3',
  'CCTV4 中文国际': 'CCTV4',
  'CCTV5 体育': 'CCTV5',
  'CCTV5+ 体育赛事': 'CCTV5+',
  'CCTV6 电影': 'CCTV6',
  'CCTV7 国防军事': 'CCTV7',
  'CCTV8 电视剧': 'CCTV8',
  'CCTV9 纪录': 'CCTV9',
  'CCTV10 科教': 'CCTV10',
  'CCTV11 戏曲': 'CCTV11',
  'CCTV12 社会与法': 'CCTV12',
  'CCTV13 新闻': 'CCTV13',
  'CCTV14 少儿': 'CCTV14',
  'CCTV15 音乐': 'CCTV15',
  'CCTV16 奥林匹克': 'CCTV16',
  'CCTV17 农业农村': 'CCTV17',
  'CCTV4K 高清': 'CCTV-4K 高清',
  'CCTV4 欧洲 HD': 'CCTV-4 中文国际',
  'CCTV4 美洲 HD': 'CCTV-4 中文国际',
  'CGTN': 'CGTN',
  'CGTN 纪录': 'CGTN纪录',
  'CCTV 阿拉伯语': 'CGTN阿语',
  'CCTV 法语': 'CGTN法语',
  'CCTV 西班牙语': 'CGTN西语',
  'CCTV 俄语': 'CGTN俄语',
  'CETV-1': 'CETV1',
  'CETV-2': 'CETV2',
  'CETV-3': 'CETV3',
  'CETV-4': 'CETV4',
  'CCTV 怀旧剧场': 'CCTV怀旧剧场',
  'CCTV 第一剧场': 'CCTV第一剧场',
  'CCTV 风云足球': 'CCTV风云足球',
  'CCTV 世界地理': 'CCTV世界地理',
  'CCTV 文化精品': 'CCTV文化精品',
  '湖南卫视': '湖南卫视',
  '江苏卫视': '江苏卫视',
  '浙江卫视': '浙江卫视',
  '东方卫视': '东方卫视',
  '北京卫视': '北京卫视',
  '深圳卫视': '深圳卫视',
  '广东卫视': '广东卫视',
  '安徽卫视': '安徽卫视',
  '东南卫视': '东南卫视',
  '河北卫视': '河北卫视',
  '黑龙江卫视': '黑龙江卫视',
  '湖北卫视': '湖北卫视',
  '江西卫视': '江西卫视',
  '辽宁卫视': '辽宁卫视',
  '海南卫视': '海南卫视',
  '山东卫视': '山东卫视',
  '四川卫视': '四川卫视',
  '天津卫视': '天津卫视',
  '重庆卫视': '重庆卫视',
  '贵州卫视': '贵州卫视',
  '吉林卫视': '吉林卫视',
  '广西卫视': '广西卫视',
  '河南卫视': '河南卫视',
  '甘肃卫视': '甘肃卫视',
  '青海卫视': '青海卫视',
  '云南卫视': '云南卫视',
  '内蒙古卫视': '内蒙古卫视',
  '山西卫视': '山西卫视',
  '陕西卫视': '陕西卫视',
  '兵团卫视': '兵团卫视',
  '新疆卫视': '新疆卫视',
  '西藏卫视': '西藏卫视',
  '宁夏卫视': '宁夏卫视',
  '延边卫视': '延边卫视',
  '康巴卫视': '康巴卫视',
  '大湾区卫视': '大湾区卫视',
  '广东珠江频道': '广东珠江',
  '厦门卫视': '厦门卫视',
  '安多卫视': '安多卫视',
  '农林卫视': '农林卫视',
  '三沙卫视': '三沙卫视',
};

export function getChannelLogoUrl(channel: IptvChannel): string {
  const logoName = channelLogoMap[channel.name];
  if (!logoName) return '';
  return `${LOGO_BASE}/${encodeURIComponent(logoName)}.png`;
}
